#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

use_frameworks!

target 'PLVRtmpDemo' do
    pod 'PLVLiveKit', '~> 1.2.4'
    pod 'PolyvLiveAPI', '~> 0.8.1'
    pod 'PolyvBusinessSDK', '~> 0.15.0'
    
    # 如果同时集成云课堂SDK，移除 PolyvBusinessSDK 即可
    #pod 'PolyvCloudClassSDK', '~> 0.13' # 最低0.13版本
end
