#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

use_frameworks!

target 'PLVRtmpDemo' do
    pod 'PLVLiveKit', '~> 1.2.4'
    pod 'PolyvLiveAPI', '~> 0.7.4'
    pod 'PolyvSocketAPI', '~> 0.6.1'
    pod 'PolyvFoundationSDK', '~> 0.10.1'
    
    # 如果同时集成云课堂SDK，则移除PolyvSocketAPI、PolyvFoundationSDK，使用云课堂SDK即可（最低0.13版本）
    #pod 'PolyvCloudClassSDK', '~> 0.13'
    
    # Xcode 10 以下解注释
    #pod 'Starscream', '3.0.5'
end
